- project:
    name: Build_Version_Text
    views:
      - 'MD Deploy Jobs'
    jobs:
      - "Build_Version"

- view-template:
    name: "MD Deploy Jobs"
    description: "Mortgage Director Deployment Jobs  "
    view-type: list
    regex: 'Deploy-MD.*|Build_Version'

- job-template:
    name: "Build_Version"
    build_text_var: "BUILD_TEXT"

    parameters:
#     Requires Validating String Plugin
      - validating-string:
          name: version
          default: "20.7.0.0"
          description: "The LOS version to deploy: X.Y.Z.a"
          regex: \d+\.\d+\.\d+\.\d+
          msg: "Version number must be 4 digits: X.Y.Z.a"

    project-type: freestyle
    defaults: global
    description: "Mortgage Director Version-To-Text"
    disabled: False
    display-name: "Mortgage Director Version-To-Text"
    concurrent: True
    quiet-period: 0
    block-downstream: False
    block-upstream: False
    retry-count: 3
    build-discarder:
      daysToKeep: 3
      numToKeep: 3

    wrappers:
      - build-user-vars
      - env-script:
          # ##################################################
          # Requires the Jenkins Environment Script Plugin.
          # Source and execute python script
          # Would need to install python on the build server
          # ##################################################
          script-content: /home/rhunt/PycharmProjects/MD_CICD/src/Utils/build_to_text.py "$version"
          script-type: unix-script
      - timestamps

    builders:
      - shell: |
          echo "Full Name: $BUILD_USER"
          echo "First Name: $BUILD_USER_FIRST_NAME"
          echo "Last Name: $BUILD_USER_LAST_NAME"
          echo "User ID: $BUILD_USER_ID"
          echo "BUILD TEXT: $VERSION_TEXT"
